import type {Metadata} from "next";
import {Geist, Geist_Mono, Inter, JetBrains_Mono} from "next/font/google";
import "./globals.css";
import {cn} from "@/shared/utils";

const jetbrainsMono = JetBrains_Mono({subsets: ['latin'], variable: '--font-mono'});

const inter = Inter({subsets: ['latin'], variable: '--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {

  const themeInitScript = `(function () {
  try {
    var saved = localStorage.getItem('theme');
    var theme = saved ? saved : (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
    var root = document.documentElement;
    root.classList.toggle('dark', theme === 'dark');
  } catch (e) {}
})();`

  return (
    <html
      lang="uk"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, inter.variable, "font-mono", jetbrainsMono.variable)}
      suppressHydrationWarning
    >
    <head>
      <script dangerouslySetInnerHTML={{__html: themeInitScript}}/>
    </head>
    <body className="min-h-screen grid grid-cols-1 grid-rows-[auto_1fr_auto]">
    {children}
    </body>
    </html>
  );
}
